// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9oVo78PjaV-6zNdcj_yPJu-s_xZnCkbE',
    appId: '1:191135381788:android:a21214ec5e14eb973b62d9',
    messagingSenderId: '191135381788',
    projectId: 'smartgridv2',
    databaseURL: 'https://smartgridv2-default-rtdb.firebaseio.com',
    storageBucket: 'smartgridv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NCcfQuOItxRPj4uXbU9WWIdz6eGy5GE',
    appId: '1:191135381788:ios:2388256cfd3dd9e83b62d9',
    messagingSenderId: '191135381788',
    projectId: 'smartgridv2',
    databaseURL: 'https://smartgridv2-default-rtdb.firebaseio.com',
    storageBucket: 'smartgridv2.appspot.com',
    androidClientId: '191135381788-eidi2j0khe7i3u4oj7sjb347u6l0iiv6.apps.googleusercontent.com',
    iosClientId: '191135381788-580rfa2nu2v6i8bsj3anlt5pofg941oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartDivNew',
  );

}